import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../assets/css/fontawesom/fontawesome.css";
import "../assets/css/fontawesom/duotone.css";
import "../assets/css/fontawesom/light.css";
import "../assets/css/fontawesom/solid.css";
import "../assets/css/fontawesom/brands.css";
import "atropos/css";
import "./globals.css";
import SmoothScrolling from "@/components/shared/SmoothScrolling";
import ToastProvider from "@/providers/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Byeto",
    description: "Generated by create next app",
    manifest : "/site.webmanifest",
};

export default function RootLayout({
                                       children
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <title>Byeto</title>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@master/devicon.min.css" />
        </head>
        <body className={"bg-background overflow-x-hidden " + inter.className}>
        <ToastProvider />
        <SmoothScrolling>
            {children}
        </SmoothScrolling>
        </body>
        </html>
    );
}
